version: '3'
services:
  app:
    build: ./web
    image: web
    ports:
      - "3000:80"
    restart: unless-stopped
  order:
    build: ./order-service
    image: order-service
    container_name: order-service
    environment:
      - NODE_ENV=development
    restart: always
    networks:
      - api-network
    ports:
      - '3001:3001'
      - '3100:3100'
    depends_on:
      - db
  payment:
    build: ./payment-service
    image: payment-service
    container_name: payment-service
    environment:
      - NODE_ENV=development
    restart: always
    networks:
      - api-network
    ports:
      - '3002:3002'
    depends_on:
      - db
  db:
    image: mongo:4.4.14
    container_name: database-mongo
    volumes: 
      - ./data_dir:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminPassword
    ports:
      - '27017:27017'
    networks:
      - api-network
    restart: always
networks:
  api-network:
    driver: bridge
